// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRsaWd1bGsIv6xkBEpcPV10dWcUQRPVU',
    appId: '1:804341168797:web:c2ccc49fd4f4ef6df9f274',
    messagingSenderId: '804341168797',
    projectId: 'hedieaety',
    authDomain: 'hedieaety.firebaseapp.com',
    storageBucket: 'hedieaety.firebasestorage.app',
    measurementId: 'G-ZHC41WFF8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIG--mnpY1qA5-9cYB8wktACipSCuY1Y',
    appId: '1:804341168797:android:1a6a7c2f27877632f9f274',
    messagingSenderId: '804341168797',
    projectId: 'hedieaety',
    storageBucket: 'hedieaety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8E_St2VwieaFSnpYKMdozPjEDW0ys_I',
    appId: '1:804341168797:ios:1c1d8f04f057865ef9f274',
    messagingSenderId: '804341168797',
    projectId: 'hedieaety',
    storageBucket: 'hedieaety.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8E_St2VwieaFSnpYKMdozPjEDW0ys_I',
    appId: '1:804341168797:ios:1c1d8f04f057865ef9f274',
    messagingSenderId: '804341168797',
    projectId: 'hedieaety',
    storageBucket: 'hedieaety.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRsaWd1bGsIv6xkBEpcPV10dWcUQRPVU',
    appId: '1:804341168797:web:75e486bf6336869cf9f274',
    messagingSenderId: '804341168797',
    projectId: 'hedieaety',
    authDomain: 'hedieaety.firebaseapp.com',
    storageBucket: 'hedieaety.firebasestorage.app',
    measurementId: 'G-RL4SBKEXZ2',
  );
}
